INSERT INTO `represented_company` (`id`, `name`, `phone`, `url`, `image`, `sort_order`) VALUES
(1, 'Aetna', '800-872-3862', 'https://www.aetna.com', '/logos/aetna.jpg', 1),
(2, 'AlwaysCare Benefits', '888-729-5433', 'http://www.alwayscarebenefits.com', '/logos/alwaysCareBenefits.jpg', 2),
(3, 'American Strategic Insurance', '866-274-8765', 'http://www.americanstrategic.com', '/logos/americanStrategicInsurance.jpg', 3),
(4, 'Auto-Owners Insurance', '800-346-0346', 'http://www.auto-owners.com/', '/logos/autoOwners.jpg', 4),
(5, 'Blue Cross Blue Shield', '800-446-8053', 'http://www.bcbsnc.com', '/logos/blueCrossBlueShield.jpg', 5),
(6, 'Builders Mutual', '800-809-4859', 'https://www.buildersmutual.com', '/logos/buildersMutual.jpg', 6),
(7, 'Community Eye Care', '888-254-4290', 'http://www.communityeyecare.net', '/logos/communityEyeCare.jpg', 7),
(8, 'Companion Life', '800-753-0404', 'http://www.companionlife.com', '/logos/companionLife.jpg', 8),
(9, 'Foremost Insurance Group', '800-527-3907', 'http://www.foremost.com', '/logos/foremostInsuranceGroup.jpg', 9),
(10, 'Guardian Life Insurance', '888-482-7342', 'https://www.guardianlife.com', '/logos/guardian.jpg', 10),
(11, 'Isurity', '336-869-3000', 'http://www.isurity.com', '/logos/isurity.jpg', 11),
(12, 'Jackson Sumner', '800-342-5572', 'https://www.jsausa.com', '/logos/jacksonSumner.jpg', 12),
(13, 'Jefferson Pilot / Lincoln Financial', '800-487-1485', 'https://www.lfg.com/public/individual', '/logos/jeffersonPilotFinancial.jpg', 13),
(14, 'Kansas City Life', '800-821-6164', 'https://www.kclife.com', '/logos/kansasCityLife.jpg', 14),
(15, 'Kemper Insurance Group', '866-860-9348', 'https://www.kemper.com', '/logos/kemperInsuranceGroup.jpg', 15),
(16, 'Liberty Mutual', '888-398-8924', 'https://www.libertymutual.com', '/logos/libertyMutual.jpg', 2),
(17, 'Main Street America Group', '800-226-0875', 'http://www.msagroup.com', '/logos/mainStreetAmericaGroup.jpg', 16),
(18, 'MetLife', '800-438-6388', 'https://www.metlife.com', '/logos/metlife.jpg', 17),
(19, 'Mutual of Omaha', '800-769-7159', 'http://www.mutualofomaha.com', '/logos/mutualOfOmaha.jpg', 18),
(20, 'National Flood Insurance Program', '800-638-6620', 'https://www.fema.gov/national-flood-insurance-program', '/logos/nationalFloodInsuranceProgram.jpg', 19),
(21, 'National General Insurance Company', '800-462-2123', 'http://www.nationalgeneral.com', '/logos/nationalGeneralInsuranceCompany.jpg', 20),
(22, 'Nationwide', '877-669-6877', 'http://www.nationwide.com', '/logos/nation.jpg', 21),
(23, 'Pennsylvania Lumbermens', '800-752-1895', 'http://www.plmilm.com', '/logos/pennsylvaniaLumbermens.jpg', 22),
(24, 'Progressive', '800-776-4737', 'http://www.progressive.com', '/logos/progressive.jpg', 23),
(25, 'SafeCo', '800-332-3226', 'http://www.safeco.com', '/logos/safeCo.jpg', 24),
(26, 'State Auto', '614-464-5000', 'https://www.stateauto.com', '/logos/stateAuto.jpg', 25),
(27, 'Tapco', '800-334-5579', 'http://www.gotapco.com', '/logos/tapco.jpg', 26),
(28, 'United Healthcare', '866-633-2446', 'http://www.uhc.com', '/logos/unitedHealthCare.jpg', 27),
(29, 'Utica National', '804-560-6600', 'http://www.uticanational.com/Insurance', '/logos/uticaNational.jpg', 28),
(30, 'United States Liability Insurance Group', '800-523-5545', 'http://www.usli.com', '/logos/unitedStatesLiabilityInsuranceGroup.jpg', 29);

INSERT INTO `state` (`id`, `abbreviation`, `name`) VALUES
(1, 'AL', 'Alabama'),
(2, 'AK', 'Alaska'),
(3, 'AZ', 'Arizona'),
(4, 'AR', 'Arkansas'),
(5, 'CA', 'California'),
(6, 'CO', 'Colorado'),
(7, 'CT', 'Connecticut'),
(8, 'DE', 'Delaware'),
(9, 'DC', 'District Of Columbia'),
(10, 'FL', 'Florida'),
(11, 'GA', 'Georgia'),
(12, 'HI', 'Hawaii'),
(13, 'ID', 'Idaho'),
(14, 'IL', 'Illinois'),
(15, 'IN', 'Indiana'),
(16, 'IA', 'Iowa'),
(17, 'KS', 'Kansas'),
(18, 'KY', 'Kentucky'),
(19, 'LA', 'Louisiana'),
(20, 'ME', 'Maine'),
(21, 'MD', 'Maryland'),
(22, 'MA', 'Massachusetts'),
(23, 'MI', 'Michigan'),
(24, 'MN', 'Minnesota'),
(25, 'MS', 'Mississippi'),
(26, 'MO', 'Missouri'),
(27, 'MT', 'Montana'),
(28, 'NE', 'Nebraska'),
(29, 'NV', 'Nevada'),
(30, 'NH', 'New Hampshire'),
(31, 'NJ', 'New Jersey'),
(32, 'NM', 'New Mexico'),
(33, 'NY', 'New York'),
(34, 'NC', 'North Carolina'),
(35, 'ND', 'North Dakota'),
(36, 'OH', 'Ohio'),
(37, 'OK', 'Oklahoma'),
(38, 'OR', 'Oregon'),
(39, 'PA', 'Pennsylvania'),
(40, 'RI', 'Rhode Island'),
(41, 'SC', 'South Carolina'),
(42, 'SD', 'South Dakota'),
(43, 'TN', 'Tennessee'),
(44, 'TX', 'Texas'),
(45, 'UT', 'Utah'),
(46, 'VT', 'Vermont'),
(47, 'VA', 'Virginia'),
(48, 'WA', 'Washington'),
(49, 'WV', 'West Virginia'),
(50, 'WI', 'Wisconsin'),
(51, 'WY', 'Wyoming');

INSERT INTO `team_member` (`id`, `first_name`, `last_name`, `suffix`, `email`, `extension`, `position`, `qualifications`, `description`, `image`, `employment_date`, `sort_order`) VALUES
(1, 'Murray', 'White', 'III', 'm3@murraymwhiteinc.com', '646', 'President', NULL, 'Murray 3, as he is known around the office, joined the family business in 1981. He has taken the lead in recent years to continue to build the Agency on the foundation that was created by his family. Murray 3 is an active agent, who assists clients in all areas of Insurance. When he is not in the office you can find him supporting High Point University Athletics or coaching a local little league baseball team. Murray 3 is happily married and excited to have his son working beside him in the family business.', '/team/murray_white_3.jpg', null, 1),
(2, 'Rick', 'Powers', NULL, 'rick@murraymwhiteinc.com', '643', 'Vice President', NULL, 'Rick is an experienced Agent with Murray White Insurance. He’s been selling policies to customers for over 23 years. While Rick is well versed in the industry, he specializes in Health Insurance. When he’s not assisting clients with their health needs, he can be found cheering on many North Carolina spots teams, as he’s a die hard Carolina Panthers, Charlotte Hornets, and UNC Chapel Hill fan. Rick is married with two kids and lives in the Triad.', '/team/rick_powers.jpg', null, 2),
(3, 'Murray', 'White', 'IV', 'm4@murraymwhiteinc.com', '638', 'Account Executive', NULL, 'Murray 4, brings some new life to Murray White Insurance. He joined the family business in December of 2013 and is continuing to learn and grow each day. Murray 4 energetically jumped on board with the Property and Casualty side of Insurance and hopes to be able to assist clients in all areas of Insurance soon. Prior to Insurance, Murray worked for the Greensboro Grasshoppers as a Sales Associate right out of college. Murray grew up playing ball at Ledford High School and went on to play baseball at High Point University. In his spare time, he loves to travel with his wife and watch Carolina Sports teams.', '/team/murray_white_4.jpg', null, 3),
(4, 'Kim', 'Milan', NULL, 'kim@murraymwhiteinc.com', '644', 'Accounting / Office Manager', NULL, 'Kim is one of the longest running associates at Murray White Insurance Agency. She’s been assisting the office in all accounting activities and Office Manager duties for over 30 years. Kim knows the business inside and out, and can be counted on by her coworkers for anything. Being a native of the Triad, Kim grew up in Trinity and then moved to Lexington with her husband to start her family. She has two wonderful grown children, and loves to read, crochet, and do crafts in her spare time. In addition, Kim is an animal lover, especially her Lab Noodles!', '/team/kim_milan.jpg', null, 4),
(5, 'Phillis', 'Butcher', NULL, 'phillis@murraymwhiteinc.com', '642', 'Personal Lines Customer Service Representative', 'CPIA', 'Phillis has been a familiar face with Murray White Insurance for 20+ years. She is originally from Georgia, but has spent the last 25 years making North Carolina home. In her spare time, you can find Phillis enjoying family time at the beach or cheering on the local baseball and softball teams. She has 2 wonderful children and 4 grandchildren that bring her and her husband great joy.', '/team/phillis_butcher.jpg', null, 5),
(6, 'Tara', 'Alexander', NULL, 'tara@murraymwhiteinc.com', '637', 'Personal Lines Customer Service Representative', NULL, 'Tara is a new employee at Murray White Insurance. We gladly welcome her to the company! She has been in the insurance industry for 14 years', '/team/tara_alexander.jpg', null, 6),
(7, 'Angie', 'McClure', NULL, 'angie@murraymwhiteinc.com', '630', 'Life &amp; Health Benefit Analyst', 'RHU, CIIP', 'Angie has been with Murray White Insurance for more than 14 years and brings over 30 years of experience in group health, life, disability, and dental insurance. At Murray White Insurance she specializes in Benefits. She’s an active member of the International Association of Insurance Professionals, and previously served as NC Association of Insurance Professionals State President. Outside of the Agency, Angie enjoys line dancing, crafts, traveling, and spending time with friends and family, especially her 4 children and 4 grand-children.', '/team/angie_mcClure.jpg', null, 7),
(8, 'Jane', 'Day', NULL, 'murraywhite@murraymwhiteinc.com', '747', 'Part Time Receptionist', NULL, 'Jane is a new employee at Murray White Insurance. We gladly welcome her to the company!', '/team/jane_day.jpg', null, 8),
(9, 'Betty', 'Callicut', NULL, '', '', '', NULL, '', '/team/betty_callicut.jpg', null, 9),
(10, 'Daniel', 'Midkiff', NULL, '', '', '', NULL, '', '/team/daniel_midkiff.jpg', null, 10),
(11, 'Fran', 'Brown', NULL, '', '', '', NULL, '', '/team/fran_brown.jpg', null, 11),
(12, 'Patty', 'Nance', NULL, '', '', '', NULL, '', '/team/pattie_nance.jpg', null, 12),
(13, 'Penny', 'Moore', NULL, '', '', '', NULL, '', '/team/penny_moore.jpg', null, 13),
(14, 'Suzanne', 'Hedgecock', NULL, '', '', '', NULL, '', '/team/suzanne_hedgecock.jpg', null, 14),
(15, 'Will', 'Suddreth', NULL, '', '', '', NULL, '', '/team/will_suddreth.jpg', null, 15);

INSERT INTO `testimonial` (`id`,  `author`, `testimonial`) VALUES
(1, 'Jonathan Pecoraro', 'I love Murray White Insurance Agency. They have been serving me well for many years. The agents are always quick to respond and willing to work with my limited budget. They have helped my family and I get back on our feet during trying times.'),
(2, 'Linda Trivetta', 'Knowledgeable and always willing to help when you call them. Very friendly staff.'),
(3, 'Dr. Joseph Fonke', 'Very helpful staff. Helped me find what our family needed as far as health insurance was concerned. Great team, great people and a group of some of the best people in all of High Point.');

INSERT INTO `global_message` (`id`,  `message`, `start_showing_date`, `stop_showing_date`) VALUES
(1, '', NOW(), NOW());

INSERT INTO `users` (`id`, `name`, `email`, `password`, `date_created`, `date_updated`) VALUES
(1, 'Jonathan Pecoraro', 'jonpecoraro@gmail.com', '$2a$10$Lz0ZNSGaWQxTuTPvoYdEhe.uFRzr0XBOBSpK7//WqD4wS6WeXIZpy', NOW(), NOW()),
(2, 'Murray White IV', 'm4@murraymwhiteinc.com', '$2a$10$Srpp8TMh6BN7/P7ZsqBSm.NgAdPk23EcuRgecN6NxY9Zu2FAMq6TC', NOW(), NOW()),
(3, 'Kim Milan', 'kim@murraymwhiteinc.com', '$2a$10$Srpp8TMh6BN7/P7ZsqBSm.NgAdPk23EcuRgecN6NxY9Zu2FAMq6TC', NOW(), NOW()),
(4, 'Robin White', 'rmwhite0119@gmail.com', '$2a$10$Srpp8TMh6BN7/P7ZsqBSm.NgAdPk23EcuRgecN6NxY9Zu2FAMq6TC', NOW(), NOW());


