INSERT INTO `represented_company` (`id`, `name`, `phone`, `url`, `image`) VALUES
(1, 'Aetna', '800-872-3862', 'https://www.aetna.com', '/img/logos/aetna.jpg'),
(2, 'AlwaysCare Benefits', '888-729-5433', 'http://www.alwayscarebenefits.com', '/img/logos/alwaysCareBenefits.jpg'),
(3, 'American Strategic Insurance', '866-274-8765', 'http://www.americanstrategic.com', '/img/logos/americanStrategicInsurance.jpg'),
(4, 'Auto-Owners Insurance', '800-346-0346', 'http://www.auto-owners.com/', '/img/logos/autoOwners.jpg'),
(5, 'Blue Cross Blue Shield', '800-446-8053', 'http://www.bcbsnc.com', '/img/logos/blueCrossBlueShield.jpg'),
(6, 'Builders Mutual', '800-809-4859', 'https://www.buildersmutual.com', '/img/logos/buildersMutual.jpg'),
(7, 'Community Eye Care', '888-254-4290', 'http://www.communityeyecare.net', '/img/logos/communityEyeCare.jpg'),
(8, 'Companion Life', '800-753-0404', 'http://www.companionlife.com', '/img/logos/companionLife.jpg'),
(9, 'Foremost Insurance Group', '800-527-3907', 'http://www.foremost.com', '/img/logos/foremostInsuranceGroup.jpg'),
(10, 'Guardian Life Insurance', '888-482-7342', 'https://www.guardianlife.com', '/img/logos/guardian.jpg'),
(11, 'Isurity', '336-869-3000', 'http://www.isurity.com', '/img/logos/isurity.jpg'),
(12, 'Jackson Sumner', '800-342-5572', 'https://www.jsausa.com', '/img/logos/jacksonSumner.jpg'),
(13, 'Jefferson Pilot / Lincoln Financial', '800-487-1485', 'https://www.lfg.com/public/individual', '/img/logos/jeffersonPilotFinancial.jpg'),
(14, 'Kansas City Life', '800-821-6164', 'https://www.kclife.com', '/img/logos/kansasCityLife.jpg'),
(15, 'Kemper Insurance Group', '866-860-9348', 'https://www.kemper.com', '/img/logos/kemperInsuranceGroup.jpg'),
(16, 'Liberty Mutual', '888-398-8924', 'https://www.libertymutual.com', '/img/logos/libertyMutual.jpg'),
(17, 'Main Street America Group', '800-226-0875', 'http://www.msagroup.com', '/img/logos/mainStreetAmericaGroup.jpg'),
(18, 'MetLife', '800-438-6388', 'https://www.metlife.com', '/img/logos/metlife.jpg'),
(19, 'Mutual of Omaha', '800-769-7159', 'http://www.mutualofomaha.com', '/img/logos/mutualOfOmaha.jpg'),
(20, 'National Flood Insurance Program', '800-638-6620', 'https://www.fema.gov/national-flood-insurance-program', '/img/logos/nationalFloodInsuranceProgram.jpg'),
(21, 'National General Insurance Company', '800-462-2123', 'http://www.nationalgeneral.com', '/img/logos/nationalGeneralInsuranceCompany.jpg'),
(22, 'Nationwide', '877-669-6877', 'http://www.nationwide.com', '/img/logos/nation.jpg'),
(23, 'Pennsylvania Lumbermens', '800-752-1895', 'http://www.plmilm.com', '/img/logos/pennsylvaniaLumbermens.jpg'),
(24, 'Progressive', '800-776-4737', 'http://www.progressive.com', '/img/logos/progressive.jpg'),
(25, 'SafeCo', '800-332-3226', 'http://www.safeco.com', '/img/logos/safeCo.jpg'),
(26, 'State Auto', '614-464-5000', 'https://www.stateauto.com', '/img/logos/stateAuto.jpg'),
(27, 'Tapco', '800-334-5579', 'http://www.gotapco.com', '/img/logos/tapco.jpg'),
(28, 'United Healthcare', '866-633-2446', 'http://www.uhc.com', '/img/logos/unitedHealthCare.jpg'),
(29, 'Utica National', '804-560-6600', 'http://www.uticanational.com/Insurance', '/img/logos/uticaNational.jpg'),
(30, 'United States Liability Insurance Group', '800-523-5545', 'http://www.usli.com', '/img/logos/unitedStatesLiabilityInsuranceGroup.jpg');

INSERT INTO `state` (`id`, `abbreviation`, `name`) VALUES
(1, 'AL', 'Alabama'),
(2, 'AK', 'Alaska'),
(3, 'AZ', 'Arizona'),
(4, 'AR', 'Arkansas'),
(5, 'CA', 'California'),
(6, 'CO', 'Colorado'),
(7, 'CT', 'Connecticut'),
(8, 'DE', 'Delaware'),
(9, 'DC', 'District Of Columbia'),
(10, 'FL', 'Florida'),
(11, 'GA', 'Georgia'),
(12, 'HI', 'Hawaii'),
(13, 'ID', 'Idaho'),
(14, 'IL', 'Illinois'),
(15, 'IN', 'Indiana'),
(16, 'IA', 'Iowa'),
(17, 'KS', 'Kansas'),
(18, 'KY', 'Kentucky'),
(19, 'LA', 'Louisiana'),
(20, 'ME', 'Maine'),
(21, 'MD', 'Maryland'),
(22, 'MA', 'Massachusetts'),
(23, 'MI', 'Michigan'),
(24, 'MN', 'Minnesota'),
(25, 'MS', 'Mississippi'),
(26, 'MO', 'Missouri'),
(27, 'MT', 'Montana'),
(28, 'NE', 'Nebraska'),
(29, 'NV', 'Nevada'),
(30, 'NH', 'New Hampshire'),
(31, 'NJ', 'New Jersey'),
(32, 'NM', 'New Mexico'),
(33, 'NY', 'New York'),
(34, 'NC', 'North Carolina'),
(35, 'ND', 'North Dakota'),
(36, 'OH', 'Ohio'),
(37, 'OK', 'Oklahoma'),
(38, 'OR', 'Oregon'),
(39, 'PA', 'Pennsylvania'),
(40, 'RI', 'Rhode Island'),
(41, 'SC', 'South Carolina'),
(42, 'SD', 'South Dakota'),
(43, 'TN', 'Tennessee'),
(44, 'TX', 'Texas'),
(45, 'UT', 'Utah'),
(46, 'VT', 'Vermont'),
(47, 'VA', 'Virginia'),
(48, 'WA', 'Washington'),
(49, 'WV', 'West Virginia'),
(50, 'WI', 'Wisconsin'),
(51, 'WY', 'Wyoming');

INSERT INTO `team_member` (`id`, `first_name`, `last_name`, `suffix`, `email`, `extension`, `position`, `qualifications`, `description`, `image`, `employment_date`, `sort_order`) VALUES
(1, 'Murray', 'White', 'III', 'm3@murraymwhiteinc.com', '646', 'Vice President', NULL, 'Murray 3, as he is known around the office, joined the family business in 1981. He has taken the lead in recent years to continue to build the Agency on the foundation that was created by his family. Murray 3 is an active agent, who assists clients in all areas of Insurance. When he is not in the office you can find him supporting High Point University Athletics or coaching a local little league baseball team. Murray 3 is happily married and excited to have his son working beside him in the family business.', '/img/team/murray_white_3.jpg', null, 1),
(2, 'Rick', 'Powers', NULL, 'rick@murraymwhiteinc.com', '643', 'Vice President', NULL, 'Rick is an experienced Agent with Murray White Insurance. He’s been selling policies to customers for over 23 years. While Rick is well versed in the industry, he specializes in Health Insurance. When he’s not assisting clients with their health needs, he can be found cheering on many North Carolina spots teams, as he’s a die hard Carolina Panthers, Charlotte Hornets, and UNC Chapel Hill fan. Rick is married with two kids and lives in the Triad.', '/img/team/rick_powers.jpg', null, 2),
(3, 'Murray', 'White', 'IV', 'm4@murraymwhiteinc.com', '638', 'Account Executive', NULL, 'Murray 4, brings some new life to Murray White Insurance. He joined the family business in December of 2013 and is continuing to learn and grow each day. Murray 4 energetically jumped on board with the Property and Casualty side of Insurance and hopes to be able to assist clients in all areas of Insurance soon. Prior to Insurance, Murray worked for the Greensboro Grasshoppers as a Sales Associate right out of college. Murray grew up playing ball at Ledford High School and went on to play baseball at High Point University. In his spare time, he loves to travel with his wife and watch Carolina Sports teams.', '/img/team/murray_white_4.jpg', null, 3),
(4, 'Kim', 'Milan', NULL, 'kim@murraymwhiteinc.com', '644', 'Accounting / Office Manager', NULL, 'Kim is one of the longest running associates at Murray White Insurance Agency. She’s been assisting the office in all accounting activities and Office Manager duties for over 30 years. Kim knows the business inside and out, and can be counted on by her coworkers for anything. Being a native of the Triad, Kim grew up in Trinity and then moved to Lexington with her husband to start her family. She has two wonderful grown children, and loves to read, crochet, and do crafts in her spare time. In addition, Kim is an animal lover, especially her Lab Noodles!', '/img/team/kim_milan.jpg', null, 4),
(5, 'Cindi', 'Michael', NULL, 'cindi@murraymwhiteinc.com', '634', 'Commercial Lines Customer Service Representative', 'CIC, CPIW', 'Cindi is a tenured associate at Murray White Insurance Agency. She has been assisting clients for the past 21 years. Cindi is a native to the Triad, having spent her whole life in Lexington. In her free time, she enjoys spending time with her family, especially her granddaughter.', '/img/team/cindi_michael.jpg', null, 5),
(6, 'Sharon', 'Idol', NULL, 'sharon@murraymwhiteinc.com', '636', 'Commercial Lines Customer Service Representative', 'CISR', 'Sharon is a welcomed new addition to Murray White Insurance! She’s been with the Agency for a year, but comes with 32+ years of insurance experience! Sharon is familiar with the area, having grown up in Forsyth County; she now resides in Davie County with her loving husband. In her free time, you can find Sharon camping, cooking, gardening, or decorating. She has one son who is currently in college studying Fire Protection and Technology.', '/img/team/sharon_idol.jpg', null, 6),
(7, 'Phillis', 'Butcher', NULL, 'phillis@murraymwhiteinc.com', '642', 'Personal Lines Customer Service Representative', 'CPIA', 'Phillis has been a familiar face with Murray White Insurance for 20+ years. She is originally from Georgia, but has spent the last 25 years making North Carolina home. In her spare time, you can find Phillis enjoying family time at the beach or cheering on the local baseball and softball teams. She has 2 wonderful children and 4 grandchildren that bring her and her husband great joy.', '/img/team/phillis_butcher.jpg', null, 7),
(8, 'Angie', 'McClure', NULL, 'angie@murraymwhiteinc.com', '630', 'Life &amp; Health Benefit Analyst', 'RHU, CIIP', 'Angie has been with Murray White Insurance for more than 14 years and brings over 30 years of experience in group health, life, disability, and dental insurance. At Murray White Insurance she specializes in Benefits. She’s an active member of the International Association of Insurance Professionals, and previously served as NC Association of Insurance Professionals State President. Outside of the Agency, Angie enjoys line dancing, crafts, traveling, and spending time with friends and family, especially her 4 children and 4 grand-children.', '/img/team/angie_mcClure.jpg', null, 8),
(9, 'Frances', 'Pope', NULL, 'murraywhite@murraymwhiteinc.com', '747', 'Receptionist / Licensing', NULL, 'Frances has been with Murray White Insurance for 5+ years and has 35+ years of experience in the Insurance Industry. Frances was originally from Tennessee, but has spent the majority of her like in the Piedmont area. Her and her husband love the mountains and spending quality time with their 2 children, 8 grand-children, and 2 great grand-children!', '/img/team/frances_pope.jpg', null, 9),
(10, 'Fran', 'Brown', NULL, 'fran@murraymwhiteinc.com', '637', 'Support', 'CISR', 'Support', '/img/team/fran_brown.jpg', null, 10),
(11, 'Suzanne', 'Hedgecock', NULL, 'suzanne@murraymwhiteinc.com', '633', 'Commercial Lines Customer Service', NULL, 'Suzanne is a new employee at Murray White Insurance. We gladly welcome her to the company!', '/img/team/suzanne_hedgecock.jpg', null, 11),
(12, 'Ricky', 'DeLappe', NULL, 'ricky@murraymwhiteinc.com', '648', 'Account Executive', NULL, 'Ricky is a new employee at Murray White Insurance. We gladly welcome him to the company!', '/img/team/ricky_deLappe.jpg', null, 12),
(13, 'Emily', 'Smith', NULL, 'emily@murraymwhiteinc.com', '639', 'Personal Lines Customer Service Representative', NULL, 'Emily is a new employee at Murray White Insurance. We gladly welcome her to the company!', '/img/team/emily_smith.jpg', null, 13);

INSERT INTO `testimonial` (`id`,  `author`, `testimonial`) VALUES
(1, 'Jonathan Pecoraro', 'I love Murray White Insurance Agency. They have been serving me well for many years. The agents are always quick to respond and willing to work with my limited budget. They have helped my family and I get back on our feet during trying times.'),
(2, 'Linda Trivetta', 'Knowledgeable and always willing to help when you call them. Very friendly staff.'),
(3, 'Dr. Joseph Fonke', 'Very helpful staff. Helped me find what our family needed as far as health insurance was concerned. Great team, great people and a group of some of the best people in all of High Point.');
